resolver: lts-16.11
extra-deps:
    - parsec-numbers-0.1.0

packages:
    - dep/xmobar
    - dep/xmonad
    - dep/xmonad-contrib

flags:
    xmobar:
        with_xft: false
        with_utf8: true
        with_threaded: true
    xmonad-contrib:
        use_xft: false
