resolver: lts-16.18
extra-deps: []

packages:
    - dep/xmobar
    - dep/xmonad
    - dep/xmonad-contrib
    - dep/X11

flags:
    xmobar:
        with_xft: false
        with_utf8: true
        with_threaded: true
    xmonad-contrib:
        use_xft: false
