resolver: lts-16.18
extra-deps:
    - parsec-numbers-0.1.0

packages:
    - dep/xmobar
    - dep/xmonad
    - dep/xmonad-contrib
    - dep/X11

flags:
    xmobar:
        with_xft: true
        with_utf8: true
        with_threaded: true
    xmonad-contrib:
        use_xft: true
