resolver: lts-16.18
extra-deps: []

packages:
    - X11
    - xmobar
    - xmonad
    - xmonad-contrib

flags:
    xmobar:
        with_xft: false
        with_utf8: true
        with_threaded: true
    xmonad-contrib:
        use_xft: false
