resolver: lts-16.18

packages:
    - X11
    - arbtt
    - ghcid
    - xmobar
    - xmonad
    - xmonad-contrib

extra-deps:
    - bytestring-progress-1.4

flags:
    xmobar:
        with_xft: false
        with_utf8: true
        with_threaded: true
    xmonad-contrib:
        use_xft: false

ghc-options:
    xmonad-contrib: '-j'
